config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :posts
    resources :users
    resources :admin_users
    resources :employees

    root to: "posts#index"
  end

  resources :posts do
    member do
      get  :approve
    end
  end
  devise_for :users, skip: [:registrations]


root to: 'static#homepage'

end

app/models/post.rb
class Post < ApplicationRecord

  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  validates_presence_of :date, :work_performed, :daily_hours

  validates :daily_hours, numericality: { greater_than: 0.0 }

  scope :posts_by, ->(user) { where(user_id: user.id) }

  after_save :confirm_audit_log, if: :submitted?
  after_save :un_confirm_audit_log, if: :rejected?

  private

  def confirm_audit_log
    audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
    audit_log.confirmed! if audit_log
  end

  def un_confirm_audit_log
    audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
    audit_log.pending! if audit_log
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:  [:show, :edit, :update, :destroy, :approve]
  def index
@posts = Post.posts_by current_user
  end

  def approve
    authorize @post
    @post.approved!
    redirect_to  root_path, notice: 'This post has been approved'
  end

  def new
    @post = Post.new
  end
def create
  @post = Post.new(post_params)
  @post.user = current_user
  if @post.save
    redirect_to @post, notice: 'Your post was created successfully'
  else
    render :new
  end

end
  def show

  end
def edit
authorize @post
end
  def update
    authorize @post

    if @post.update_attributes(post_params)
      redirect_to @post, notice:  'Your post was successfully updated'
    else
      render :edit
    end

  end

  def destroy
    if @post.delete
        redirect_to posts_path, notice: 'Your post was successfully deleted'
    else
      render :index
    end

  end
  private

  def post_params
    params.require(:post).permit(:date, :work_performed, :status, :daily_hours)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper


end

app/views/posts/_form.html.erb
<%= form_for @post, html: { class: 'form-horizontal' } do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |error| %>
            <%= js add_gritter(error, title: "Overtime App Notification", sticky: false) %>
        <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :daily_hours, class: 'col-sm-2 control-label' %>
      <%= f.text_field :daily_hours, class: 'form-control' %>
    </div>
<div class="form-group">
  <%= f.label :date, class: 'col-sm-2 control-label' %>
  <%= f.date_field :date, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :work_performed, class: 'col-sm-2 control-label' %>
  <%= f.text_area :work_performed, class: 'form-control' %>
</div>


    <%= render partial: 'status', locals: {f: f} if current_user.type == 'AdminUser'  %>
    <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
 >
  <td>
    <%= post.daily_hours %>
  </td>
  <td>
    <%= post.date %>
  </td>
  <td class="hidden-xs">
    <%= link_to truncate(post.work_performed), post %>
  </td>
  <td>
   <%= status_label post.status %>
  </td>
  <td>
    <%= link_to '', edit_post_path(post), id: "edit_#{post.id}", class: 'glyphicon glyphicon-pencil index-icons' if policy(post).update? %>
  </td>
  <td>
    <%= link_to '', post_path(post), method: :delete ,id: "delete_post_#{post.id}_from_index", data: { confirm: 'Are u sure?'}, class: 'glyphicon glyphicon-trash index-icons'  %>
  </td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'approved' %>
  <%= f.label :status, 'Approved' %>

  <%= f.radio_button :status, 'rejected' %>
  <%= f.label :status, 'Rejected' %>

</div>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>


    <th>
      Hours
    </th>
    <th>
      Date
    </th>
    <th class="hidden-xs">
      work_performed
    </th>
    <th>
      Status
    </th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1></h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div>
  <h2><%= @post.work_performed %></h2>
</div>

<div class="well">
  <div>
    <h3> <span>Hours worked:</span> <%= @post.daily_hours %></h3>
  </div>
  <div>
    <h3> <span>Date:</span> <%= @post.date %></h3>
  </div>
  <div>
    <h3><span>Employee:</span> <%= @post.user.full_name %></h3>
  </div>
  <div>
    <h3><span>Current stage of approval:</span> <%= @post.status %> </h3>
  </div>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' if policy(@post).update? %>